server:
  port: 8000

spring:
  application:
    name: BAND_GATEWAY_SERVICE
  cloud:
    gateway:
      # cors setting ..
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
      routes:
        # example template..

        - id: board-service
          uri: "lb://BOARD-SERVICE"
          predicates:
            - Path=/api/v1/comment/**

        - id: LIKE-SERVICE
          uri: "lb://LIKE-SERVICE"
          predicates:
            - Path=/api/v1/like/**

        - id: ALBUM-SERVICE
          uri: "lb://ALBUM-SERVICE"
          predicates:
            - Path=/api/v1/album/**

        - id: SCHEDULE-SERVICE
          uri: "lb://SCHEDULE-SERVICE"
          predicates:
            - Path=/api/v1/scedule/**

        - id: BAND-USER-SERVICE
          uri: "lb://BAND-USER-SERVICE"
          predicates:
            - Path=/api/v1/bandMember/**

# Config Server Observing Update..
management:
  endpoints:
    web:
      exposure:
        include: health,beans,refresh

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true








