server:
  port: 8000

spring:
  application:
    name: BAND_GATEWAY_SERVICE
  cloud:
    gateway:
      # cors setting ..
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
      routes:
        # example template..

        #- id: auth-service
        #  uri: "lb://AUTH-SERVICE"
        #  predicates:
        #    - Path=/api/v1/auth/**

# Config Server Observing Update..
management:
  endpoints:
    web:
      exposure:
        include: health,beans,refresh

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true








