server:
  port: 8000

spring:
  application:
    name: BAND-GATEWAY-SERVICE
  cloud:
    gateway:

      # cors setting ..
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
      routes:
        # example template..

        - id: BAND-USER-SERVICE
          uri: "lb://BAND-USER-SERVICE"
          predicates:
            - Path=/api/v1/user/**

        - id: BAND-USER-SERVICE
          uri: "lb://BAND-USER-SERVICE"
          predicates:
            - Path=/api/v1/interest/**

        - id: BAND-COMMUNITY-SERVICE
          uri: "lb://BAND-COMMUNITY-SERVICE"
          predicates:
            - Path=/api/v1/community/**

# Config Server Observing Update..
management:
  endpoints:
    web:
      exposure:
        include: health,beans,refresh

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}









